GET http://localhost:3000/api/categories

###
GET http://localhost:3000/api/categories/6460a2e7126f6cf1cd7fde93

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Pakaian",
    "description": "Semua jenis yang berhubungan pakaian"
}

###
PATCH  http://localhost:3000/api/categories/6460a1c7ede56945b3947864
Content-Type: application/json

{
    "name": "Pakaian",
    "description": "Semua jenis yang berhubungan pakaian BARU"
}

###
DELETE   http://localhost:3000/api/categories/6460a2e7126f6cf1cd7fde93