GET http://localhost:3000/api/categories

###
GET http://localhost:3000/api/categories/6460a55784416fa4ba20960f

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Pakaian",
    "description": "Semua jenis yang berhubungan pakaian"
}

###
PATCH  http://localhost:3000/api/categories/6460a55784416fa4ba20960f
Content-Type: application/json

{
    "name": "Pakaian baru"
}

###
DELETE   http://localhost:3000/api/categories/6460a55784416fa4ba20960f